multiple pools 2
xpdlDefinition_VariousMultiplePools

	^'<?xml version="1.0" encoding="utf-8"?>
<Package xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Id="7a32c2ce-1859-49e7-81c6-d52d4810cb58" Name="Diagram 1" xmlns="http://www.wfmc.org/2009/XPDL2.2">
  <PackageHeader>
    <XPDLVersion>2.2</XPDLVersion>
    <Vendor>Bizagi Process Modeler.</Vendor>
    <Created>2016-07-08T11:50:35.9406729-03:00</Created>
    <ModificationDate>2016-07-08T14:28:33.442983-03:00</ModificationDate>
    <Description>Diagram 1</Description>
    <Documentation />
  </PackageHeader>
  <RedefinableHeader>
    <Author>Usuario</Author>
    <Version>1.0</Version>
    <Countrykey>CO</Countrykey>
  </RedefinableHeader>
  <ExternalPackages />
  <Pools>
    <Pool Id="b433546e-481c-4f98-9429-b07a96d776ec" Name="Main Process" Process="f82caeb7-823e-4952-98f6-ba1ad17964f3" BoundaryVisible="false">
      <Lanes />
      <NodeGraphicsInfos>
        <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="350" Width="700" BorderColor="-16777216" FillColor="-1">
          <Coordinates XCoordinate="30" YCoordinate="30" />
        </NodeGraphicsInfo>
      </NodeGraphicsInfos>
    </Pool>
    <Pool Id="aea83da5-4e68-4040-87ba-5999cecf76ee" Name="Process 1" Process="ac2026ce-3711-4d01-b753-61820888fe8d" BoundaryVisible="true">
      <Lanes>
        <Lane Id="449af12e-9647-4289-ad1c-c6eacc88a6d3" Name="Lane 2" ParentPool="aea83da5-4e68-4040-87ba-5999cecf76ee">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="82" Width="424" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="0" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
        <Lane Id="e50f0f06-1c72-45bf-b718-26e315fa8b71" Name="Lane 3" ParentPool="aea83da5-4e68-4040-87ba-5999cecf76ee">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="69" Width="424" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="82" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
        <Lane Id="a8e66475-10ed-40ad-b55d-f8aae0a603b3" Name="Lane 1" ParentPool="aea83da5-4e68-4040-87ba-5999cecf76ee">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="85" Width="424" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="151" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
      </Lanes>
      <NodeGraphicsInfos>
        <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="236" Width="474" BorderColor="-16777216" FillColor="-1">
          <Coordinates XCoordinate="29" YCoordinate="29" />
        </NodeGraphicsInfo>
      </NodeGraphicsInfos>
    </Pool>
    <Pool Id="b624b0f9-05f9-41b6-b6ec-620b48352e96" Name="Process 2" Process="79357901-9d0f-44e7-8390-038955a3614b" BoundaryVisible="true">
      <Lanes>
        <Lane Id="added31c-85e3-4889-8397-caf0a181201b" Name="Lane 5" ParentPool="b624b0f9-05f9-41b6-b6ec-620b48352e96">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="150" Width="478" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="0" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
        <Lane Id="d25dd234-6bd2-457c-87be-10bef0c360bf" Name="Lane 4" ParentPool="b624b0f9-05f9-41b6-b6ec-620b48352e96">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="158" Width="478" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="150" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
      </Lanes>
      <NodeGraphicsInfos>
        <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="308" Width="528" BorderColor="-16777216" FillColor="-1">
          <Coordinates XCoordinate="516" YCoordinate="27" />
        </NodeGraphicsInfo>
      </NodeGraphicsInfos>
    </Pool>
    <Pool Id="73fecaab-92ca-4930-ba19-c55be25b80cc" Name="Process 3" Process="c2db903e-8c1a-4186-9c38-f8b9d836f692" BoundaryVisible="true">
      <Lanes>
        <Lane Id="780f6cbb-314f-4c79-bdd5-c78ce57834c7" Name="Lane 7" ParentPool="73fecaab-92ca-4930-ba19-c55be25b80cc">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="86" Width="431" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="0" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
        <Lane Id="a7be7b65-41dc-4aa5-a532-0290ba17b88c" Name="Lane 6" ParentPool="73fecaab-92ca-4930-ba19-c55be25b80cc">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="82" Width="431" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="86" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
      </Lanes>
      <NodeGraphicsInfos>
        <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="168" Width="481" BorderColor="-16777216" FillColor="-1">
          <Coordinates XCoordinate="280" YCoordinate="361" />
        </NodeGraphicsInfo>
      </NodeGraphicsInfos>
    </Pool>
    <Pool Id="4a1e0ec4-d771-4b76-a3c0-fa7f803d5ced" Name="Process 4" Process="8181a5a4-d693-4665-8b42-4bfcc92f1d23" BoundaryVisible="true">
      <Lanes>
        <Lane Id="55266abd-9854-4ca6-bfd4-f043f62bb40c" Name="Lane 9" ParentPool="4a1e0ec4-d771-4b76-a3c0-fa7f803d5ced">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="154" Width="200" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="0" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
        <Lane Id="7164c650-e099-42c9-a647-ec0f8c65c29f" Name="Lane 8" ParentPool="4a1e0ec4-d771-4b76-a3c0-fa7f803d5ced">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="157" Width="200" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="154" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
      </Lanes>
      <NodeGraphicsInfos>
        <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="311" Width="250" BorderColor="-16777216" FillColor="-1">
          <Coordinates XCoordinate="791" YCoordinate="355" />
        </NodeGraphicsInfo>
      </NodeGraphicsInfos>
    </Pool>
    <Pool Id="bfd8299c-98c5-46f3-90ea-2441be1c8695" Name="Process 5" Process="38f559f3-e3b6-4f99-b906-ae34fa282c3c" BoundaryVisible="true">
      <Lanes>
        <Lane Id="07697df3-6d50-44cd-b654-bbf3ac654838" Name="Lane 10" ParentPool="bfd8299c-98c5-46f3-90ea-2441be1c8695">
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="184" Width="711" BorderColor="-11513776" FillColor="-1">
              <Coordinates XCoordinate="50" YCoordinate="0" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Lane>
      </Lanes>
      <NodeGraphicsInfos>
        <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="184" Width="761" BorderColor="-16777216" FillColor="-1">
          <Coordinates XCoordinate="3" YCoordinate="544" />
        </NodeGraphicsInfo>
      </NodeGraphicsInfos>
    </Pool>
  </Pools>
  <WorkflowProcesses>
    <WorkflowProcess Id="f82caeb7-823e-4952-98f6-ba1ad17964f3" Name="Main Process">
      <ProcessHeader>
        <Created>2016-07-08T14:29:00.0424968-03:00</Created>
        <Description />
      </ProcessHeader>
      <RedefinableHeader>
        <Author />
        <Version />
        <Countrykey>CO</Countrykey>
      </RedefinableHeader>
      <ActivitySets />
      <DataInputOutputs />
      <ExtendedAttributes>
        <ExtendedAttribute Name="RuntimeProperties" Value="{&quot;processClassProperties&quot;:{&quot;displayName&quot;:&quot;Main Process&quot;,&quot;accessType&quot;:&quot;Process&quot;,&quot;enableAlarms&quot;:false,&quot;enableNotifications&quot;:false,&quot;creationDate&quot;:&quot;2016-07-08T11:50:35.9416736-03:00&quot;},&quot;processProperties&quot;:{&quot;versionCreationDate&quot;:&quot;2016-07-08T11:50:35.9416736-03:00&quot;,&quot;supportsScopes&quot;:false,&quot;formsVersion&quot;:0}}" />
      </ExtendedAttributes>
    </WorkflowProcess>
    <WorkflowProcess Id="ac2026ce-3711-4d01-b753-61820888fe8d" Name="Process 1">
      <ProcessHeader>
        <Created>2016-07-08T14:29:00.0424968-03:00</Created>
        <Description />
      </ProcessHeader>
      <RedefinableHeader>
        <Author />
        <Version />
        <Countrykey>CO</Countrykey>
      </RedefinableHeader>
      <ActivitySets />
      <DataInputOutputs />
      <Activities>
        <Activity Id="f77494b8-5c2b-4d88-8309-4e3f17e4210d" Name="pr1_start">
          <Description />
          <Event>
            <StartEvent Trigger="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-10311914" FillColor="-1638505">
              <Coordinates XCoordinate="247" YCoordinate="48" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes>
            <ExtendedAttribute Name="RuntimeProperties" Value="{}" />
          </ExtendedAttributes>
        </Activity>
        <Activity Id="891ea8a1-bfb8-4ab0-9b95-210c4d7688ab" Name="Task 1">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="127" YCoordinate="117" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="82170314-0ec7-4c5d-9c61-f3001af6bd23" Name="Task 2">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="272" YCoordinate="186" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="702f9f3f-79c4-455f-8d8f-45e6d0fa576c" Name="pr1_end2">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="405" YCoordinate="201" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="6bd642ce-6331-4ae8-8603-e2aa3c35dbe1" Name="pr1_end1">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="157" YCoordinate="213" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
      </Activities>
      <Transitions>
        <Transition Id="10c6c538-f9b1-4f4c-8bb6-266559950fbd" From="f77494b8-5c2b-4d88-8309-4e3f17e4210d" To="891ea8a1-bfb8-4ab0-9b95-210c4d7688ab" Name="tr: start t1">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="262" YCoordinate="78" />
              <Coordinates XCoordinate="262" YCoordinate="95" />
              <Coordinates XCoordinate="172" YCoordinate="95" />
              <Coordinates XCoordinate="172" YCoordinate="117" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="224aa1d5-0fef-4c1f-8f85-f602f9dc1db6" From="891ea8a1-bfb8-4ab0-9b95-210c4d7688ab" To="82170314-0ec7-4c5d-9c61-f3001af6bd23" Name="tr: t1 t2">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="217" YCoordinate="147" />
              <Coordinates XCoordinate="234" YCoordinate="147" />
              <Coordinates XCoordinate="234" YCoordinate="216" />
              <Coordinates XCoordinate="272" YCoordinate="216" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="3f96d668-07e9-4e44-b543-d4dfc6d39c18" From="82170314-0ec7-4c5d-9c61-f3001af6bd23" To="702f9f3f-79c4-455f-8d8f-45e6d0fa576c" Name="tr: t2 end2">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="362" YCoordinate="216" />
              <Coordinates XCoordinate="405" YCoordinate="216" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="dbd76257-9dd9-4e38-9d02-3dccd8b92f7e" From="891ea8a1-bfb8-4ab0-9b95-210c4d7688ab" To="6bd642ce-6331-4ae8-8603-e2aa3c35dbe1" Name="tr: t1 end1">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="172" YCoordinate="177" />
              <Coordinates XCoordinate="172" YCoordinate="213" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
      </Transitions>
      <ExtendedAttributes>
        <ExtendedAttribute Name="RuntimeProperties" Value="{&quot;processClassProperties&quot;:{&quot;accessType&quot;:&quot;Process&quot;,&quot;enableAlarms&quot;:false,&quot;enableNotifications&quot;:false,&quot;creationDate&quot;:&quot;2016-07-08T11:50:35.9426734-03:00&quot;},&quot;processProperties&quot;:{&quot;versionCreationDate&quot;:&quot;2016-07-08T11:50:35.9426734-03:00&quot;,&quot;supportsScopes&quot;:false,&quot;formsVersion&quot;:0}}" />
      </ExtendedAttributes>
    </WorkflowProcess>
    <WorkflowProcess Id="79357901-9d0f-44e7-8390-038955a3614b" Name="Process 2">
      <ProcessHeader>
        <Created>2016-07-08T14:29:00.0675151-03:00</Created>
        <Description />
      </ProcessHeader>
      <RedefinableHeader>
        <Author />
        <Version />
        <Countrykey>CO</Countrykey>
      </RedefinableHeader>
      <ActivitySets />
      <DataInputOutputs />
      <Activities>
        <Activity Id="0a1333e4-5bc2-45c7-8998-b820c6530703" Name="pr2_start">
          <Description />
          <Event>
            <StartEvent Trigger="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-10311914" FillColor="-1638505">
              <Coordinates XCoordinate="616" YCoordinate="46" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes>
            <ExtendedAttribute Name="RuntimeProperties" Value="{}" />
          </ExtendedAttributes>
        </Activity>
        <Activity Id="0ec26871-17f0-4c21-9bd4-34de8cd6ad15" Name="Task 3">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="725" YCoordinate="31" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="982bf83f-72fd-46ac-9515-842a9f8ec8f2" Name="Task 4">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="878" YCoordinate="31" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="92ea0a72-d846-4edb-aa0e-6a2833e607a5" Name="Task 5">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="896" YCoordinate="186" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="d12a785d-835f-42d2-8f5b-fd209896f1d3" Name="Task 6">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="766" YCoordinate="111" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="6ac41377-ac84-48d3-9751-1d50be016216" Name="Task 7">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="641" YCoordinate="185" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="ada88ece-ea06-4368-898c-fb59aa414c92" Name="pr2_end2">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="671" YCoordinate="287" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="295e96e9-4d3f-4f36-9449-51cebc351791" Name="Task 8">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="896" YCoordinate="272" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="2da6b9aa-09a6-40bb-a642-424b0e68dc00" Name="pr2_end1">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="796" YCoordinate="226" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
      </Activities>
      <Transitions>
        <Transition Id="7015d1c7-6a70-46d8-a2e0-0beb5f7b965a" From="0a1333e4-5bc2-45c7-8998-b820c6530703" To="0ec26871-17f0-4c21-9bd4-34de8cd6ad15" Name="tr: start t3">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="646" YCoordinate="61" />
              <Coordinates XCoordinate="725" YCoordinate="61" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="a3821d1a-d5b1-4cc3-bd8a-9fdb96dcd224" From="0ec26871-17f0-4c21-9bd4-34de8cd6ad15" To="982bf83f-72fd-46ac-9515-842a9f8ec8f2" Name="tr: t3 t4">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="815" YCoordinate="61" />
              <Coordinates XCoordinate="878" YCoordinate="61" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="4c99b7e0-6070-465f-b79d-38c1fb20bd1f" From="982bf83f-72fd-46ac-9515-842a9f8ec8f2" To="92ea0a72-d846-4edb-aa0e-6a2833e607a5" Name="tr: t4 t5">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="923" YCoordinate="91" />
              <Coordinates XCoordinate="923" YCoordinate="138.5" />
              <Coordinates XCoordinate="941" YCoordinate="138.5" />
              <Coordinates XCoordinate="941" YCoordinate="186" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="54d82288-e216-4416-89d4-f60ddd62724b" From="92ea0a72-d846-4edb-aa0e-6a2833e607a5" To="d12a785d-835f-42d2-8f5b-fd209896f1d3" Name="tr: t5 t6">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="896" YCoordinate="216" />
              <Coordinates XCoordinate="873.5" YCoordinate="216" />
              <Coordinates XCoordinate="873.5" YCoordinate="141" />
              <Coordinates XCoordinate="856" YCoordinate="141" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="692b3bbe-8d0a-4a48-8f01-079bc9ae8087" From="d12a785d-835f-42d2-8f5b-fd209896f1d3" To="6ac41377-ac84-48d3-9751-1d50be016216" Name="tr: t6 t7">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="766" YCoordinate="141" />
              <Coordinates XCoordinate="752.5" YCoordinate="141" />
              <Coordinates XCoordinate="752.5" YCoordinate="215" />
              <Coordinates XCoordinate="731" YCoordinate="215" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="f23f1bf9-79ec-4823-a243-0ca42a6a67c3" From="6ac41377-ac84-48d3-9751-1d50be016216" To="ada88ece-ea06-4368-898c-fb59aa414c92" Name="tr: t7 end2">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="686" YCoordinate="245" />
              <Coordinates XCoordinate="686" YCoordinate="287" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="0c2fb34c-980d-4b43-8d27-0071546843f6" From="92ea0a72-d846-4edb-aa0e-6a2833e607a5" To="295e96e9-4d3f-4f36-9449-51cebc351791" Name="tr: t5 t8">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="941" YCoordinate="246" />
              <Coordinates XCoordinate="941" YCoordinate="272" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="5e9298ab-26c4-4843-abb6-c83f8e29bd66" From="295e96e9-4d3f-4f36-9449-51cebc351791" To="ada88ece-ea06-4368-898c-fb59aa414c92" Name="tr: t8 end2">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="896" YCoordinate="302" />
              <Coordinates XCoordinate="701" YCoordinate="302" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="bef8ac2e-083b-4b49-a082-c2c703f57445" From="d12a785d-835f-42d2-8f5b-fd209896f1d3" To="2da6b9aa-09a6-40bb-a642-424b0e68dc00" Name="tr: t6 end1">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="811" YCoordinate="171" />
              <Coordinates XCoordinate="811" YCoordinate="226" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
      </Transitions>
      <ExtendedAttributes>
        <ExtendedAttribute Name="RuntimeProperties" Value="{&quot;processClassProperties&quot;:{&quot;accessType&quot;:&quot;Process&quot;,&quot;enableAlarms&quot;:false,&quot;enableNotifications&quot;:false,&quot;creationDate&quot;:&quot;2016-07-08T11:52:10.0501493-03:00&quot;},&quot;processProperties&quot;:{&quot;versionCreationDate&quot;:&quot;2016-07-08T11:52:10.0501493-03:00&quot;,&quot;supportsScopes&quot;:false,&quot;formsVersion&quot;:0}}" />
      </ExtendedAttributes>
    </WorkflowProcess>
    <WorkflowProcess Id="c2db903e-8c1a-4186-9c38-f8b9d836f692" Name="Process 3">
      <ProcessHeader>
        <Created>2016-07-08T14:29:00.068514-03:00</Created>
        <Description />
      </ProcessHeader>
      <RedefinableHeader>
        <Author />
        <Version />
        <Countrykey>CO</Countrykey>
      </RedefinableHeader>
      <ActivitySets />
      <DataInputOutputs />
      <Activities>
        <Activity Id="79652b6f-1d6f-4fe1-b76c-3ad32869f526" Name="pr3_start">
          <Description />
          <Event>
            <StartEvent Trigger="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-10311914" FillColor="-1638505">
              <Coordinates XCoordinate="365" YCoordinate="390" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes>
            <ExtendedAttribute Name="RuntimeProperties" Value="{}" />
          </ExtendedAttributes>
        </Activity>
        <Activity Id="75619f23-d2d9-4581-b26e-a96d2e395c60" Name="Task 9">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="444" YCoordinate="375" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="f658643a-cf77-46e0-99f4-28833dab30d7" Name="Task 10">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="588" YCoordinate="375" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="4f2e28a0-fd24-45aa-8237-f816f07db605" Name="Task 11">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="657" YCoordinate="462" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="5649bd94-7a57-4a8c-afc1-a4ff79286712" Name="Task 12">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="500" YCoordinate="462" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="2cf70c39-cc61-46e4-9cfc-b24a2a8a4482" Name="pr3_end">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="404" YCoordinate="477" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
      </Activities>
      <Transitions>
        <Transition Id="62115651-c1fd-4731-b91d-7cb6d6b88957" From="79652b6f-1d6f-4fe1-b76c-3ad32869f526" To="75619f23-d2d9-4581-b26e-a96d2e395c60" Name="tr: start t9">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="395" YCoordinate="405" />
              <Coordinates XCoordinate="444" YCoordinate="405" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="056898a1-77a3-471d-9d4c-a338f1a311b9" From="75619f23-d2d9-4581-b26e-a96d2e395c60" To="f658643a-cf77-46e0-99f4-28833dab30d7" Name="tr: t9 t10">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="534" YCoordinate="405" />
              <Coordinates XCoordinate="588" YCoordinate="405" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="a895fc8e-bae7-4607-bb51-0c9a29b513a6" From="f658643a-cf77-46e0-99f4-28833dab30d7" To="4f2e28a0-fd24-45aa-8237-f816f07db605" Name="tr: t10 t11">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="678" YCoordinate="416" />
              <Coordinates XCoordinate="702" YCoordinate="416" />
              <Coordinates XCoordinate="702" YCoordinate="462" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="c44be328-d7b1-4e7f-a8f5-6757d08e6b1f" From="4f2e28a0-fd24-45aa-8237-f816f07db605" To="5649bd94-7a57-4a8c-afc1-a4ff79286712" Name="tr: t11 t12">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="657" YCoordinate="492" />
              <Coordinates XCoordinate="590" YCoordinate="492" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="6475e7db-e4e0-4842-9e85-1ca8422781c1" From="5649bd94-7a57-4a8c-afc1-a4ff79286712" To="2cf70c39-cc61-46e4-9cfc-b24a2a8a4482" Name="tr: t12 end">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="500" YCoordinate="492" />
              <Coordinates XCoordinate="434" YCoordinate="492" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
      </Transitions>
      <ExtendedAttributes>
        <ExtendedAttribute Name="RuntimeProperties" Value="{&quot;processClassProperties&quot;:{&quot;accessType&quot;:&quot;Process&quot;,&quot;enableAlarms&quot;:false,&quot;enableNotifications&quot;:false,&quot;creationDate&quot;:&quot;2016-07-08T11:53:11.2628898-03:00&quot;},&quot;processProperties&quot;:{&quot;versionCreationDate&quot;:&quot;2016-07-08T11:53:11.2628898-03:00&quot;,&quot;supportsScopes&quot;:false,&quot;formsVersion&quot;:0}}" />
      </ExtendedAttributes>
    </WorkflowProcess>
    <WorkflowProcess Id="8181a5a4-d693-4665-8b42-4bfcc92f1d23" Name="Process 4">
      <ProcessHeader>
        <Created>2016-07-08T14:29:00.068514-03:00</Created>
        <Description />
      </ProcessHeader>
      <RedefinableHeader>
        <Author />
        <Version />
        <Countrykey>CO</Countrykey>
      </RedefinableHeader>
      <ActivitySets />
      <DataInputOutputs />
      <Activities>
        <Activity Id="ec78141d-7b88-46be-af86-cadb97a52aed" Name="pr4_start">
          <Description />
          <Event>
            <StartEvent Trigger="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-10311914" FillColor="-1638505">
              <Coordinates XCoordinate="928" YCoordinate="381" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes>
            <ExtendedAttribute Name="RuntimeProperties" Value="{}" />
          </ExtendedAttributes>
        </Activity>
        <Activity Id="d2de2da2-f9e9-42c9-800b-d3cad06d6911" Name="Task 13">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="898" YCoordinate="446" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="6b7af09b-fc91-4d99-b808-4a2033e1afe3" Name="Task 14">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="898" YCoordinate="520" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="b05c04dd-6d0b-41ba-8f45-5200e026dd45" Name="pr4_end2">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="928" YCoordinate="611" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="06d1ad6e-3888-4e9b-ab76-f8a25cb9c5e1" Name="pr4_end1">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="1013" YCoordinate="461" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
      </Activities>
      <Transitions>
        <Transition Id="a4f22283-1f13-460e-a7fc-7992ac723995" From="ec78141d-7b88-46be-af86-cadb97a52aed" To="d2de2da2-f9e9-42c9-800b-d3cad06d6911" Name="tr: start t13">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="943" YCoordinate="411" />
              <Coordinates XCoordinate="943" YCoordinate="446" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="9fc2444b-2eb9-43da-8d9e-942fe1858357" From="d2de2da2-f9e9-42c9-800b-d3cad06d6911" To="6b7af09b-fc91-4d99-b808-4a2033e1afe3" Name="tr: t13 t14">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="943" YCoordinate="506" />
              <Coordinates XCoordinate="943" YCoordinate="520" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="50901038-4825-4e5a-9896-12cc0f87ec1a" From="6b7af09b-fc91-4d99-b808-4a2033e1afe3" To="b05c04dd-6d0b-41ba-8f45-5200e026dd45" Name="tr: t14 end2">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="943" YCoordinate="580" />
              <Coordinates XCoordinate="943" YCoordinate="611" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="012b351c-65ac-476c-b364-17c1940f48e7" From="d2de2da2-f9e9-42c9-800b-d3cad06d6911" To="06d1ad6e-3888-4e9b-ab76-f8a25cb9c5e1" Name="tr: t13 end1">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="988" YCoordinate="476" />
              <Coordinates XCoordinate="1013" YCoordinate="476" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
      </Transitions>
      <ExtendedAttributes>
        <ExtendedAttribute Name="RuntimeProperties" Value="{&quot;processClassProperties&quot;:{&quot;accessType&quot;:&quot;Process&quot;,&quot;enableAlarms&quot;:false,&quot;enableNotifications&quot;:false,&quot;creationDate&quot;:&quot;2016-07-08T11:53:58.8725235-03:00&quot;},&quot;processProperties&quot;:{&quot;versionCreationDate&quot;:&quot;2016-07-08T11:53:58.8725235-03:00&quot;,&quot;supportsScopes&quot;:false,&quot;formsVersion&quot;:0}}" />
      </ExtendedAttributes>
    </WorkflowProcess>
    <WorkflowProcess Id="38f559f3-e3b6-4f99-b906-ae34fa282c3c" Name="Process 5">
      <ProcessHeader>
        <Created>2016-07-08T14:29:00.068514-03:00</Created>
        <Description />
      </ProcessHeader>
      <RedefinableHeader>
        <Author />
        <Version />
        <Countrykey>CO</Countrykey>
      </RedefinableHeader>
      <ActivitySets />
      <DataInputOutputs />
      <Activities>
        <Activity Id="4a17d75f-cb9b-4105-8133-0f8cb03cfd65" Name="pr5_start">
          <Description />
          <Event>
            <StartEvent Trigger="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-10311914" FillColor="-1638505">
              <Coordinates XCoordinate="118" YCoordinate="563" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes>
            <ExtendedAttribute Name="RuntimeProperties" Value="{}" />
          </ExtendedAttributes>
        </Activity>
        <Activity Id="54a20b17-6b37-4121-a8fe-65bae707f527" Name="Task 15">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="226" YCoordinate="548" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="d841b5a9-396c-4495-aa08-5a5715a41009" Name="Task 16">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="657" YCoordinate="548" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="9bfa62ca-bb50-48ae-a6f1-bc08246f8cb6" Name="Task 17">
          <Description />
          <Implementation>
            <Task />
          </Implementation>
          <Performers />
          <Documentation />
          <Loop LoopType="None" />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="60" Width="90" BorderColor="-16553830" FillColor="-1249281">
              <Coordinates XCoordinate="657" YCoordinate="640" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="563f37b9-814e-4c15-a2d9-4200f2663e1f" Name="pr5_end2">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="544" YCoordinate="655" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
        <Activity Id="64f335cf-c155-4372-a85a-4b4fd09b7296" Name="pr5_end1">
          <Description />
          <Event>
            <EndEvent Result="None" />
          </Event>
          <Documentation />
          <NodeGraphicsInfos>
            <NodeGraphicsInfo ToolId="BizAgi_Process_Modeler" Height="30" Width="30" BorderColor="-6750208" FillColor="-1135958">
              <Coordinates XCoordinate="256" YCoordinate="660" />
            </NodeGraphicsInfo>
          </NodeGraphicsInfos>
          <ExtendedAttributes />
        </Activity>
      </Activities>
      <Transitions>
        <Transition Id="8fbfa35a-e69e-4ad8-96b7-f31cbce54c9f" From="4a17d75f-cb9b-4105-8133-0f8cb03cfd65" To="54a20b17-6b37-4121-a8fe-65bae707f527" Name="tr: start t15">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="148" YCoordinate="578" />
              <Coordinates XCoordinate="226" YCoordinate="578" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="462cc8f6-1999-42cf-8329-2109ce2fba62" From="54a20b17-6b37-4121-a8fe-65bae707f527" To="d841b5a9-396c-4495-aa08-5a5715a41009" Name="tr: t15 t16">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="316" YCoordinate="578" />
              <Coordinates XCoordinate="657" YCoordinate="578" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="0d38a024-fde1-44f3-aa6a-70c64d016d53" From="d841b5a9-396c-4495-aa08-5a5715a41009" To="9bfa62ca-bb50-48ae-a6f1-bc08246f8cb6" Name="tr: t16 t17">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="702" YCoordinate="608" />
              <Coordinates XCoordinate="702" YCoordinate="640" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="724540b7-7225-409a-a89d-c1d195b5c81e" From="9bfa62ca-bb50-48ae-a6f1-bc08246f8cb6" To="563f37b9-814e-4c15-a2d9-4200f2663e1f" Name="tr: t17 end2">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="657" YCoordinate="670" />
              <Coordinates XCoordinate="574" YCoordinate="670" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
        <Transition Id="8100ef2d-019c-4026-a55f-31613aa04b1a" From="54a20b17-6b37-4121-a8fe-65bae707f527" To="64f335cf-c155-4372-a85a-4b4fd09b7296" Name="tr: t15 end1">
          <Condition />
          <Description />
          <ConnectorGraphicsInfos>
            <ConnectorGraphicsInfo ToolId="BizAgi_Process_Modeler" BorderColor="-16777216">
              <Coordinates XCoordinate="271" YCoordinate="608" />
              <Coordinates XCoordinate="271" YCoordinate="660" />
            </ConnectorGraphicsInfo>
          </ConnectorGraphicsInfos>
          <ExtendedAttributes />
        </Transition>
      </Transitions>
      <ExtendedAttributes>
        <ExtendedAttribute Name="RuntimeProperties" Value="{&quot;processClassProperties&quot;:{&quot;accessType&quot;:&quot;Process&quot;,&quot;enableAlarms&quot;:false,&quot;enableNotifications&quot;:false,&quot;creationDate&quot;:&quot;2016-07-08T11:54:55.3865225-03:00&quot;},&quot;processProperties&quot;:{&quot;versionCreationDate&quot;:&quot;2016-07-08T11:54:55.3865225-03:00&quot;,&quot;supportsScopes&quot;:false,&quot;formsVersion&quot;:0}}" />
      </ExtendedAttributes>
    </WorkflowProcess>
  </WorkflowProcesses>
  <ExtendedAttributes />
</Package>'