other
style

^'/* Smart Devices*/
@media (max-width: 800px) {                  
   .smart-hide-width {
      display: none !important;
   }
}
@media (max-height: 450px) {                  
   .smart-hide-height {
      display: none !important;
   }
}
/* NEW CSS - REFACTORIZED */
/* START: HTML GENERAL */
body, html, main {
	margin: 0;
	width: 100%;
	height: 100%;
	overflow-y: hidden;
	background-color: #BCBCBC;
}
#screen-all {
	height: 100%;
}
/* END: HTML GENERAL */
.main-static-msg-div {
	margin-left: auto;
	margin-right: auto;
	width: 60%;
	margin-top: 80px;
	font-family: arial;
}
.static-msg-title {
	font-size: 28px;
	margin: 15px;
}
.static-msg-text {
	font-size: 22px;
	margin: 15px;
}
.static-msg-data {
	font-size: 20px;
	margin: 15px;
}'