style
style2

	^super style,
'/* START: FRONT OFFICE STYLES */
#assignation-close-form form fieldset {
  border: 0px;
}
.assignation-title {
  font-size: 20px;
  text-align: center;
  margin-bottom: 15px;
  margin-top: 10px;
  text-decoration: underline;
}
.centered-forms {
  margin-left: 1%;
  margin-right: 2%;
  margin-top: 1%;
}
.centered-forms-width38 {
  width: 38%;
}
.centered-forms form { 
  border-radius: 10px;
  border-style: inset;
  background-color: #7A7557;
  padding: 5px;
  border-width: 2px;
  width: 100%;
}
.centered-forms form fieldset {
  border: none;
} 
.centered-forms form input[type="text"]{ 
  border-radius: 10px;
  border-style: inset;
  width: 350px;
  margin-bottom: 5px;
}
.centered-forms form input[type="submit"] { 
  border-radius: 10px;
  width: 150px;
  border-right: 10px;
  margin-left: 3%;
  margin-right: 3%;
  margin-top: 1%;
}
.centered-forms form input[type="file"] { 
  border-radius: 10px;
  width: 400px;
  border-right: 10px;
  margin-top: 10px;
  margin-bottom: 5px;
}
.centered-forms form label { 
  display: block;
  margin-top: 10px;
}
.centered-forms form select { 
  border-radius: 10px;
  border-style: inset;
  display: block;
  width: 350px;
  margin-bottom: 10px;
}
.centered-forms form p { 
  margin-top: 10px;
  font-size: 20px;
  font-style: italic;
  text-align: right;
}
.centered-forms legend {
  text-align: center;
  font-size: 20px;
  color: black;
}
.centered-forms output {
  text-align: center;
  font-size: 16px;
  color: #EADDDD;
}
.centered-forms ul {
  border-radius: 15%;
  background-color: #F5F5DC;
}
.free-selected-process {
  float: right;
}
#free-tasks-list {
  overflow-y: auto;
}
#free-tasks-list ul {
  list-style-type: none;
  margin-top: 0px;
}
.free-tasks-list-hide-top {
  height: 86%;
}
.free-tasks-list-show-top {
  height: 77%;
}
#granted-transitions {
  width: 60%;
  margin-left: auto;
  margin-right: auto;
}
.item-customized-component-hide-top {
  height: 74%;
}
.item-customized-component-show-top {
  height: 65%;
}
.monitor-list-icon {
  float: left;
  display: inline;
}
.monitor-list-icon-2 {
  float: right;
  display: inline;
}
.monitor-list-icon-height75 {
  height: 75px;
}
.monitor-list-icon-height90 {
  height: 110px;
}
.monitor-list-item-data {}
.monitor-list-item-data span {
  font-style: italic;
}
.monitor-list-item-data output {
  color: #231D81;
  margin-left: 10px;
  float: right;
}
.monitor-list-item-summary {
  display: inline-block;
    margin: 20px;
    padding: 20px;
    background-color: white;
    border-radius: 10px;
}
.monitor-list-item-summary span {
  font-style: italic;
}
.new-process-options {
    width: 50%;
    float: left;
}
#new-process-options-form {
  display: inline-flex;
}
#new-process-list  ul {
  list-style-type: none;
  margin-top: 0px;
}
#orbeon-form-frame {
  height: 400px;
} 
#orbeon-form {
  height: 100%;
}
#orbeon-form iframe {
  width: 100%;
  height: 100%;
}
#process-assigment-transitions {
  margin-left: 10px;
  margin-top: 10px;
  overflow-y: auto;
  height: 440px;
}
.process-transition-icon-collapse {
  float: right;
}
.process-transition-finished {
  padding: 15px;
  padding-top: 5px;
  float: left;
  margin: 10px 10px 10px 10px;
  border-radius: 25px;
  background-color: #8CBD80;
  width: 28%;
  height: 60%;
  overflow-y: auto;
  box-shadow: 0px 0px 3px 0px rgba(11, 10, 10, 0.8);
}
.process-transition-gateway {
  padding: 15px;
  padding-top: 5px;
  float: left;
  margin: 10px 10px 10px 10px;
  border-radius: 25px;
  background-color: #ADADAD;
  width: 28%;
  height: 60%;
  overflow-y: auto;
}
.process-transition-running {
  padding: 15px;
  padding-top: 5px;
  float: left;
  margin: 10px 10px 10px 10px;
  border-radius: 25px;
  width: 28%;
  height: 60%;
  overflow-y: auto;
  background-color: #80A0BD;
  box-shadow: 0px 0px 3px 0px rgba(11, 10, 10, 0.8);
}
.process-transition-collapsed {
  height: 1%;
}
.process-transition-expanded {
  height: 60%;
}
.transition-data span {
  margin-right: 20px;
  font-style: italic;
  color: #565656;
    display: inline-table;
}
.transition-data output  {
  color: rgb(50, 51, 122);
  float: right;
}
.unique-wide-list-icon {
  width: 2.5%;
  float: left;
  display: inline;
}
.unique-wide-list-icon-height75 {
  height: 75px;
}
.unique-wide-list-icon-height90 {
  height: 110px;
}
.unique-wide-list-item-data {}
.unique-wide-list-item-data span {
  font-style: italic;
}
.unique-wide-list-item-data output {
  color: #231D81;
  margin-left: 10px;
}
.unique-wide-list-item-summary {}
.unique-wide-list-item-summary span {
  font-style: italic;
}
/* END: FRONTOFFICE STYLES-*/
'