other
style

	^'
h1 {margin-left: 35px;}
body {
	margin-bottom: 25px !important;
	background-color: darkgrey;
}
#application-links {
	display: flex;
	margin: 40px auto 0 auto;
	width: 620px;
}
.application-link { }
.application-link figcaption {text-align: center}
#flags {
	display: flex;
	margin: 0 auto;
	width: 170px;
}
#flags img {
	margin-right: 5px;
}
.flag {
	float: left;
}
.flag-last {
	margin-right: 10px;
}
.form-link {
    margin-top: 20px;
    display: flex;
    margin: 40px auto 0 auto;
    width: 360px;
    font-size: larger;
}
.form-link a {
    text-decoration: none;
    background-color: gray;
    padding: 10px;
    border-radius: 8px;
}
#header {
	display: flex;
	margin: 40px auto 0 auto;
	width: 360px;
	font-size: xx-large;
}
#no-environment {
	display: flex;
	margin: 40px auto 0 auto;
	width: 315px;
	font-size: x-large;
	color: red;
}
'