other
csvExample1

	^'Environment;Application;AppType;RoleName;RoleType;IsAdmin;UserName
ibm;ibm.sales;O;administrator;F;true;robert
ibm;ibm.sales;O;administrator;F;true;andrew
ibm;ibm.budget;B;administrator;F;true;juan
google;google.marketing;B;administrator;F;true;alan
google;google.marketing;B;administrator;B;true;alan
google;google.admins;B;admin;B;true;google.admin
ibm;ibm.admins;B;admin;B;true;ibm.admin'