other
createOrbeonForms

	testRoot buildPublishedFormNamed: 'emit-visa' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_emit_visa in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'analyze-appliance' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_analyze_appliance in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'check-previous-appliance' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_check_previous_appliance in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'check-basic-data' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_check_basic_data in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'citizen-appliance' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_citizen_appliance in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'financial-report' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_financial_report in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'check-debts' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_check_debts in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'check-properties' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_check_properties in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'check-accounts' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_check_accounts in: self getDefaultApplication.
	
	testRoot buildPublishedFormNamed: 'applicant-home-office-report' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_applicant_home_office_report in: self getDefaultApplication.

	testRoot buildPublishedFormNamed: 'check-applicant-record' title: '' withXml: testRoot newDefinitionTemplate formDefinition_ue_check_applicant_record in: self getDefaultApplication.