other
languageFlagsIconsAndNames

	^OrderedCollection new
		add: (Array with: #germanyflag24Png with: 'Deutsch' with: #german);
		add: (Array with: #unitedkingdomflag24Png with: 'English' with: #english);
		add: (Array with: #spainflag24Png with: 'Español' with: #spanish);
		add: (Array with: #franceflag24Png with: 'Français' with: #french);
		add: (Array with: #italyflag24Png with: 'Italiano' with: #italian);
		add: (Array with: #portugalflag24Png with: 'Português' with: #portuguese);
		yourself