style
style

	^super style,
'/* START: BACK OFFICE STYLES */
#add-new-import-form {
  display: inline-flex;
  margin-top: 10px;
}
#add-new-form-button {
  padding: 10px;
}
#add-rol-button {
  float: left;
  margin-top: 20px;
}
#add-user-button {
  float: left;
  margin-top: 40px;
}
#applications-list {
  float: left;
  margin-left: 10px;
}
#applications-list select {
  width: 300px;
}
#forms-operations {
  float: left;
  width: 200px;
}
#forms-operations input {
  border-radius: 10px;
  margin-left: 10px;
  margin-bottom: 10px;
}
.import-all-button-1 {
  padding: 10px;
}
.import-all-button-2 {
  margin-top: 10px;
  margin-left: 10px;
}
.import-csv-info {
  background-color: beige;
  padding: 10px;
  border-radius: 15px;
  border: 2px solid green;
}
#import-forms {
  overflow-y: auto;
  display: inline-block;
  width: 100%;
  bottom: 0px;
  position: absolute;
  max-height: 100%;
  top: 112px;
}
#internationalization {
}
#internationalization fieldset {
  border: medium none;
}
#internationalization label, #internationalization input, #internationalization select {
  width: 200px;
  border-radius: 10px;
  margin-right: 15px;
}
#inter-current-dictionary {
  height: 480px;
  margin-left: auto;
  margin-right: auto;
  width: 90%;
  overflow-y: auto;
}
#inter-current-dictionary output {
  color: #66650B;
}
#inter-current-dictionary span {
  color: rgb(14, 79, 101);
}
#orbeon-definitions-list {
  padding-top: 10px;
  float: left;
}
#orbeon-list-application {
  padding-top: 20px;
  float: left;
}
#radar {
  display: inline-flex;
}
#remove-new-form-button {
  padding-top: 10px;
}
#rols-users {
  padding-bottom: 20px;
}
#rols-and-users {
  float: left;
  display: inline-flex;
}
#system-rols {
  display: inline-flex;
  float: left;
}
#system-users {
  display: inline-flex;
  float: left;
}
#users-and-rols {
  float: left;  
}
#users-configuration {
}
#user-rols {
}
#users-to-add-to-role {
  float: left;
}
#users-to-add-to-role input {
  border-radius: 10px;
}
#users-to-add-to-role input[type="submit"] {
  margin-top: 20px;
}
.transition-condition {
  padding-top: 20px;
  padding-bottom: 20px;
  padding-left: 40px;
  padding-right: 40px;
  background-color: lightgray;
  border-radius: 30px;
}
.transition-def-artifact {
    padding-top: 20px;
    padding-left: 40px;
    padding-right: 40px;
    background-color: #868686;
    border-radius: 10px;
}
/* END: BACK OFFICE STYLES */
'