baseline
baseline: spec
  <baseline>
   spec
     for: #'common'
     do: [
       spec package: 'OrbeonBPMCore'.
       spec package: 'OrbeonBPMRuntime'.
       spec package: 'OrbeonBizagiReader2'.
       spec package: 'OrbeonBPMXpdl'.
       spec package: 'OrbeonBPMWeb'.
       spec package: 'OrbeonBPMWebBackoffice'.
       spec package: 'OrbeonPersistenceApiProcess'.
       spec package: 'OrbeonBizagiReader2_Tests'.
       spec package: 'OrbeonBPMXpdl_Tests'.
       spec package: 'OrbeonBPMRuntime_Tests'.
		]